### ISSUE TITLE
Feature Request: Access Token Authentication for Firefly III instances behind Keycloak/Authelia

### ISSUE THREAD

**Issue by victorbalssa** [victorbalssa/abacus#93]
- implementing access token as a 2nd option for authentication.
 - Could Fix #89 and #90

**Comment by paulcalabro** [comment]
@victorbalssa Can you please confirm if these Authelia settings are required for this feature to work?

```
access_control:
  rules:
    - domain:
        - <domain_goes_here>
      resources:
        - ^/api/v1/.*$
      policy: bypass
```
